[package]
name = "effigy-api"
version = "0.1.0"
edition = "2021"
description = "an image service for serving and manipulating images"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
